import type { Metadata } from "next";
import "./globals.css";
import { NavigationProvider } from "@/providers";
import { Header, NavigationMenu } from "@/components";
import ReduxProvider from "@/store/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased pl-17 bg-[#e9eef6] h-screen">
        <div className="bg-[#f8fafd] flex flex-col h-full">
          <Header />
          <div className="flex flex-1 min-h-0">
            <ReduxProvider>
              <NavigationProvider>
                <NavigationMenu />
                <div className="flex-1 pr-14 pb-4 min-w-0">{children}</div>
              </NavigationProvider>
            </ReduxProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
