import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased pl-17 bg-[#e9eef6]">
        <div className="bg-[#f8fafd]">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
